@startuml
abstract  Context
interface Strategy
entity    ConcreteStrategyA
entity    ConcreteStrategyB
Context *-- Strategy
Strategy <|-- ConcreteStrategyA
Strategy <|-- ConcreteStrategyB
Strategy : +execute()
ConcreteStrategyA : +execute()
ConcreteStrategyB : +execute()
@enduml